export const INPUT_CHANGE = 'INPUT_CHANGE';

export const CHANGE_FORM = 'CHANGE_FORM';

export const SEND_USER_DATA_PENDING = 'SEND_USER_DATA_PENDING';
export const SEND_USER_DATA_SUCCESS = 'SEND_USER_DATA_SUCCESS';
export const SEND_USER_DATA_FAILED = 'SEND_USER_DATA_FAILED';
